config/routes.rb
Rails.application.routes.draw do
  # get 'users/index'
  get 'users/show'
  # devise_for :users

  # devise_for :users do
  #   get '/users/sign_out' => 'devise/sessions#destroy'
  # end
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth' }
  # devise_for :users, :controllers => {:registrations => 'users/registrations', :omniauth_callbacks =>'users/omniauth' }

  # devise_for :users, controllers: { :registrations => 'users/registrations',omniauth_callbacks: 'users/omniauth' }
    # devise_for :users, controllers: { :registrations => 'users/registrations', sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth' }
  
  get 'posts/index'
  get 'posts/new' 
  get 'posts/show'
  get 'posts/create'
  get 'posts/edit'
  get 'posts/update'
  get 'posts/destroy'
  post 'draft', to: 'posts#draft'
  get 'posts/draft_show'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"
  # root "homes#index"

  # get 'posts/search' => 'posts#search'
  get "posts/download"
  # get 'cities/:state', to: 'application#cities'
  get 'usera/state' => 'users#state'

  resources :posts
  # resources :states, only: :index
  get 'sign_up', to: 'states#index'
  get 'towns', to: 'towns#city'

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def index
	end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-danger">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">


      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <% if user_signed_in? %> 

        <li class="nav-item">
          <%= link_to 'Posts', posts_index_path, class:"navbar-brand"%>
        </li>
       
        <li class="nav-item">   
          <%= link_to 'Add Post', posts_new_path, class:"nav-link text-dark"%>  
        </li>

        <li class="nav-item">   
          <%= link_to 'Draft Post', posts_draft_show_path, class:"nav-link text-dark"%>  
        </li>

        <li class="nav-item">
          <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link text-dark"%>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign Out', destroy_user_session_path, class:"nav-link text-dark"  %>
        </li>

        <li class="nav-item">
          <%= link_to 'My Profile', users_show_path, class:"nav-link text-dark"  %>
        </li>
      <% else %>  
      
        <li class="nav-item">
          <%= link_to 'Posts', posts_index_path, class:"navbar-brand"%>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign In', new_user_session_path, class:"nav-link text-dark"%>
        </li>

        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link text-dark" %>
        </li>
      <% end %>   
      </ul>

      <%= form_with url: posts_index_path, method: :get do |form| %>
        <%= form.text_field :search %>
        <%= form.submit "Search" %>
      <% end %>
    
    </div>
  </div>
</nav>

app/views/homes/index.html.erb
<h1>HOME INDEX PAGE </h1>