config/routes.rb
Rails.application.routes.draw do
  # get 'users/index'
  get 'users/show'
  # devise_for :users

  # devise_for :users do
  #   get '/users/sign_out' => 'devise/sessions#destroy'
  # end
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth' }
  # devise_for :users, :controllers => {:registrations => 'users/registrations', :omniauth_callbacks =>'users/omniauth' }

  # devise_for :users, controllers: { :registrations => 'users/registrations',omniauth_callbacks: 'users/omniauth' }
    # devise_for :users, controllers: { :registrations => 'users/registrations', sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth' }
  
  get 'posts/index'
  get 'posts/new' 
  get 'posts/show'
  get 'posts/create'
  get 'posts/edit'
  get 'posts/update'
  get 'posts/destroy'
  post 'draft', to: 'posts#draft'
  get 'posts/draft_show'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"
  # root "homes#index"

  # get 'posts/search' => 'posts#search'
  get "posts/download"
  # get 'cities/:state', to: 'application#cities'
  get 'usera/state' => 'users#state'

  resources :posts
  # resources :states, only: :index
  get 'sign_up', to: 'states#index'
  get 'towns', to: 'towns#city'

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  # validates :title, format: {with: /\A[A-Za-z\s]+\z/, message: "only letters are allowed"}, presence: true
  # validates :description, length: {minimum: 50, message: "is too short please type again"}, presence: true

  enum state: {draft: 0, published: 1 }

  mount_uploader :attachment, AttachmentUploader



#Search Bar Query
  # def self.search(search)
  #   if search
  #     where("title iLIKE ?", "%#{search}%").order("title")
  #     # joins(:user).where("name iLIKE ?", "%#{search}%").order("posts.id desc")
  #     # where("")
  #   else   
  #     all
  #   end
  # end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  skip_before_action :verify_authenticity_token
  
  def index
    # @posts = Post.search(params[:search])
    @posts = Post.where(state: "published").paginate(:page => params[:page], :per_page => 6).order(:id)
    # debugger
     respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @action = 'new'
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
    # render json: @post
  end

  def create
    @post = current_user.posts.new(post_params) #link every post with user 
    
    if @post.save!
      redirect_to posts_index_path, notice: "post created successfully"
      PostSendMail.new(@post).send_mail      #Using services for Sending mail 
    else
      render 'new'
    end
  end

  def edit
    @action = 'edit'
     @post = Post.find(params[:id])
     render 'edit'
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to posts_index_path, notice: "post was successfully updated"
    else
      render "edit"
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_index_path, notice: "post was successfully deleted"
  end

  def draft
      @post = current_user.posts.new(post_params)
      if @post.save
        @post.update(state: "draft");
        # debugger
      end

  end

  def draft_show
    @drafts = Post.where(state: "draft")
  end



  # def search
  #   @posts = Post.search(params[:search])
  # end

  # def download
  #   post = Post.find(params[:id]).attachment.url
  #   send_file Rails.root.join("uploads/#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}", post), type: 'image/jpeg'
  # end

  # def pdf    
  #       file_name = params[:feed_image_path].split('/').last
  #       @filename ="#{Rails.root}/public/uploads/feed_image/feedimage/#{file_name}"
  #       send_file(@filename ,
  #         :type => 'application/pdf/docx/html/htm/doc',
  #         :disposition => 'attachment')           
  # end

 private
  def post_params
    params.require(:post).permit( :title, :description, :attachment )
  end


  # def user_signed?
  #   if user_signed_in?
  #     redirect_to new_user_session
  #   else
  #     redirect_to posts_index_path  
  #   end
  # end
  

end

app/helpers/posts_helper.rb
module PostsHelper

	# def user_name(post)
	# 	post.present? and post.user.name.present? ? "#{ (post.user.name).capitalize}" : ''
	# end


	# def title(post)
	# 	post.present? ? "#{(post.title).capitalize}" : ""
	# end

end

app/views/posts/_form.html.erb
<div class="d-flex justify-content-center align-item-center">
    <%= form_with  class: "form", model: @post, url: @action == 'edit' ? post_path : posts_path, method: @action == 'edit' ? :PATCH : :POST do |form| %>
      <%= form.label :title,  "Title:" %><br>
      <%= form.text_field :title, class:'form-control input', id:'post_title' %><br>
      <%= form.label :description, "Description:" %><br>
      <%= form.text_area :description , class:'form-control input', id:'post_description'%><br>
      <%= form.label :attachment %><br>
      <%= form.file_field :attachment, class:'form-control input' %><br>
      <input id="draft-btn" type="button" value="Save As Draft" name= 'draft'></input> 
      <input id="submit-btn" type="button" value="Publish" name= 'publish' ></input>  

    <% end %>
</div>

<%= javascript_include_tag "draft" %>


<script type="text/javascript">
var regTitle = /^[a-zA-Z\s]{3,}$/
var regDesc = /(.){50,}/
var inputArray = document.querySelectorAll(".input");
var form = document.querySelector(".form");
var regArray = [regTitle, regDesc]
var alertArray = ['Tilte can only contains letter', 'Description must be of more than 50  words']
var inputBlank = ['title must be present', "description must be present"]
var array = [];
var submitBtn = document.querySelector("#submit-btn");


submitBtn.addEventListener("click", validation);
function validation(e) {
  errorAlert = []
  blankErrorAlert = []
  for (var i = 0; i < inputArray.length; i++) {
    array.push(inputArray[i].value);
    console.log(array);
    if (!regArray[i].test(array[i]) && array[i] != "") {
      alert(alertArray[i]);
      errorAlert.push(alertArray[i]);
      break;
    }else if (array[i] == "") {
      alert(inputBlank[i]);
      blankErrorAlert.push(inputBlank[i]);
      break;
    }
    if (errorAlert.legth > 0 || blankErrorAlert.length > 0) {
      e.preventDefault()
      return false
    }else {
      console.log('form submitted')
      form.submit()
    }
  }
    
}
</script>

app/views/posts/_post.html.erb
  <% @posts.each do |post| %>
    <% if post.state == 'published'%>
      <tr style="height: 200px;" >
        <td class="border-1   "><%= post.user.name %></td>
        <td class="border-1 "><%= post.id %></td>
        <td class="border-1  "><%= post.title %></td>
        <td class="border-1 "><%= post.description %></td>

        <% if user_signed_in? %>
          <td class="border-1">
            <div class="d-flex justify-content-center">
              <% if post.user_id == current_user.id %>
                <%= button_to 'Delete', post_path(post), method: :delete, data: {confirm: "Are You Sure?"}, class:'btn  btn-danger delete-btn submitDel', id:"delBtn" %>
                <%= button_to 'Edit', edit_post_path(post), method: :get%>
              <% end %>
                <%= button_to 'Show', post_path(post), method: :get %>             
            </div>
          </td>
        <% end %>
      </tr>   
    <% end %>
  <% end %>  
      
          

app/views/posts/create.html.erb
<h1>Posts#create</h1>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/draft_show.html.erb
<table class="d-flex justify-content-center">
        <h1 class="text-center"> Users Posts </h1>
          <tr>
            <th class="border-1 p-2 text-center">User Name</th>
            <th class="border-1 p-2 text-center">ID</th>
            <th class="border-1 p-2 text-center ">Title </th>
            <th class="border-1 p-2 text-center">Description</th>

            <% if user_signed_in? %>
              <th class="border-1 p-2 text-center">Actions</th>
            <% end %>
          </tr>
          <% @drafts.each do |post| %>
          <% if post.user_id == current_user.id %>
              <tr>
                  <td class="border-1 p-2 ">
                      <%= post.user.name %>
                  </td>
                  <td class="border-1 p-2 ">
                      <%= post.id %>
                  </td>
                  <td class="border-1 p-2 ">
                      <%= post.title %>
                  </td>
                  <td class="border-1 p-2 ">
                      <%= post.description %>
                  </td>
                
                  <% if user_signed_in? %>
                    <td colspan="3" class="d-flex border-1 p-2 align-items-center" style="height: 5rem;">
                    <% if post.user_id == current_user.id %>
                      <%= button_to 'Delete', post_path(post), method: :delete, data: {confirm: "Are You Sure?"}, class:'btn  btn-danger delete-btn submitDel', id:"delBtn" %>          
                      <%= button_to 'Edit', edit_post_path(post), method: :get%>
                      <%= button_to 'Show', post_path(post), method: :get %>
                    <% end %>
                    </td>
                  <% end %>
              </tr>   
          <% end %>
          <% end %>
          
        <%# end %>
</table>
<br>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>
<% if @post.user == current_user %>
	<%= render 'form' %>
<% else%>	
	<div><p>You Can't Edit Other User Post  </p></div>
<% end %>	

<script type="text/javascript">
$(function() {
  $('#showall').click(function() {
    $('.targetDiv').show();
  });
  $('.showSingle').click(function() {
    $('.targetDiv').hide();
    $('#div' + $(this).attr('target')).show();
  });
});
</script>

<div class="buttons">
  <a id="showall">All</a>
  <a class="showSingle" target="1">Div 1</a>
  <a class="showSingle" target="2">Div 2</a>
  <a class="showSingle" target="3">Div 3</a>
  <a class="showSingle" target="4">Div 4</a>
</div>

<div id="div1" class="targetDiv">Lorum Ipsum1</div>
<div id="div2" class="targetDiv">Lorum Ipsum2</div>
<div id="div3" class="targetDiv">Lorum Ipsum3</div>
<div id="div4" class="targetDiv">Lorum Ipsum4</div>

app/views/posts/index.html.erb
<div class="container" id="my-posts">
  <table class="d-flex justify-content-center">
    <h1 class="text-center"> Users Posts </h1>
    <% unless @posts.present? %>
        <div class="text-center bg-light  p-5">You Don't Have Any Post Yet</div>
        <!-- <p >NO post yet... Create Post</p> -->
    <% else %>
      <tr>
        <th class="border-1 ">User Name</th>
        <th class="border-1 ">ID</th>
        <th class="border-1  ">Title </th>
        <th class="border-1 ">Description</th>

        <% if user_signed_in? %>
          <th class="border-1 ">Actions</th>
        <% end %>
      </tr>
      <tr>
        
        <%= render 'posts/post'%>
      </tr>
    <% end %>
  </table>
</div>



<div id="infinite-scrolling">
  <%= will_paginate @posts%>
</div>

<%= javascript_include_tag "pagination" %>

<script type="text/javascript">
  $(document).ready(function() {
    var deleteBtn = document.querySelectorAll('.delete-btn');
    function confirmDelete(e) {
       console.log("Fuction")
       
      if (confirm("Are you sure?")) {
        console.log("Yes");
      } else {
        console.log("no");
        event.preventDefault();
      }
    
  }
  for(var i = 0; i < deleteBtn.length; i++){
      deleteBtn[i].addEventListener("click", confirmDelete);
  }
});

</script>

app/views/posts/index.js.erb
$('#my-posts').append("<%= j render 'posts/post' %>");
<% if @posts.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate @posts %>');
<% else %>
  $(window).off('scroll');
  $('.pagination').remove();
<% end %>

app/views/posts/new.html.erb
<h1>Posts#new</h1>

<%= render 'form' %>

app/views/posts/search.html.erb
<strong class="fs-1 fw-light"><%= user_name(@post) %></strong>
<p>Hello Search</p>

<%= render @posts %>

app/views/posts/show.html.erb
<div class="d-flex justify-content-center p-2">
  <div><strong class="fs-1 fw-light"><%= @post.user.name  %></strong>
    <hr>
    <strong>Title: </strong><%= @post.title %><br><br>
    <strong>Description:</strong><%= @post.description %><br><br>
  </div>
</div>

<div class="p-2 text-center">
  <%if @post.attachment.url %>
    <strong>Image:</strong><br>
    <%= image_tag @post.attachment.url, width:200, height:300, alt: "Uploaded image"  %><br>
    <%= link_to  "click to Download", @post.attachment.url, download: "", class: "btn btn-primary mt-2" %>
  <% end %>
</div>
<br><br>

<div class="d-flex justify-content-center ">
    <%= link_to 'Back', posts_index_path, class:"btn btn-primary " %>
    <% if @post.user == current_user %>
    <%= link_to 'Edit', edit_post_path, class:"btn btn-primary" %>
    <%= button_to 'Delete', post_path(@post), method: :delete, data: {confirm: "Are You Sure?"}, class:'btn btn-danger delete-btn'%>
    <% end %>
</div>

<script type="text/javascript">
$(document).ready(function() {
    var deleteBtn = document.querySelector(".delete-btn")
    deleteBtn.addEventListener("click", confirmDelete)

    function confirmDelete(e) {
            console.log("Function")
        let confirmed = "are you sure?"

        if (confirm(confirmed)) {
            console.log("Yes");

        } else {
            console.log("no");
            event.preventDefault()
        }
    }
});
</script>

app/views/posts/update.html.erb
<h1>Posts#update</h1>